auto: true
permalink: /blog/:year/:month/:day/:title
exclude:
- README.md
- .gitignore

menu: 
  main:
    - name: home
      url: "/"
    - name: about

  web:
    - name: GitHub
      url: https://github.com/fkling
  
    - name: Stackoverflow
      url: http://stackoverflow.com/users/218196/felix-kling

  creations:
    - name: FloatNotes
    
    - name: jQuery Function Toggle
      url: /pages/jquery_function_toggle.html